application:
  hooks:
    build-actions: npm-run-all mkdir esbuild zip
  actions: actions
  runtimeManifest:
    packages:
      adobeio-samples-react-ssr:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: 'nodejs:16'
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
